//
//  BuildInfo.swift
//  CheckrSpot
//
//  Auto-generated file - DO NOT EDIT
//  This file is generated by the "Generate Build Info" build phase
//

import Foundation

struct BuildInfo {
    static let gitCommitSHA: String = "7f43c4e20a79a4be06c6947985404eaa7aa58b42"
    static let buildNumber: String = "79"
    static let marketingVersion: String = "1.0.4"
}
